run:
  allow-parallel-runners: true
linters-settings: 
    funlen:
        lines: 80
    errcheck: 
        exclude: errcheck_excludes.txt
    revive:
      rules:
        - name: var-naming
          arguments: [["ID"]]
linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - bidichk
    - cyclop 
    - deadcode
    - depguard
    - decorder
    - dogsled
    # - dupl
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - revive
    - scopelint
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

  # don't enable:
  # - godox
  # - maligned,prealloc
  # - gochecknoglobals
  # - golint
  # - gochecknoinits
